###########################################
# THIS IS A TEMPLATE DOCKER CONFIGURATION #
# UN(COMMENT) FOR YOUR OWN USAGE          #
###########################################

version: '3'

networks: 
    phpsrv:

volumes:
    maria:
    #mysql:
    #pgdata:
    #redis:

services: 
    #############
    # DATABASES #
    #############
    mariadb:
        image: mariadb:10.7
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: madb
            MYSQL_TCP_PORT: 3306
        volumes:
            - ${HOST_DIRECTORY}/.docker/data/mariadb/my.cnf:/etc/mysql/my.cnf:ro
            - ${HOST_DIRECTORY}/.docker/data/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf:ro
            - ${HOST_DIRECTORY}/.docker/data/mariadb/conf.d/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
            - maria:/var/lib/mysql
        # Port is set in MYSQL_TCP_PORT
        networks:
            - ${NETWORK}

    # mysql:
    #     image: mysql:8.0
    #     container_name: mysql
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: pass
    #         MYSQL_DATABASE: mydb
    #         MYSQL_TCP_PORT: 3307
    #     volumes:
    #         - ${HOST_DIRECTORY}/.docker/data/mysql/my.cnf:/etc/mysql/my.cnf:ro
    #         - ${HOST_DIRECTORY}/.docker/data/mysql/conf.d/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    #         - ${HOST_DIRECTORY}/.docker/data/mysql/initdb.d/:/docker-entrypoint-initdb.d/:ro
    #         - mysql:/var/lib/mysql
    #     # Port is set in MYSQL_TCP_PORT
    #     networks: 
    #         - ${NETWORK}

    # postgres:
    #     image: postgres:latest #12.4
    #     restart: always
    #     environment:
    #         POSTGRES_USER: user
    #         POSTGRES_PASSWORD: pass
    #         POSTGRES_DB: pgdb
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - pgdata:/var/lib/postgresql/data
    #     networks:
    #         - ${NETWORK}

    ##############
    # Key-values #
    ##############
    # redis:
    #     image: redis:latest #6.0  
    #     restart: always
    #     volumes: 
    #         - ${HOST_DIRECTORY}/.docker/data/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    #         - redis:/data
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - ${NETWORK}
    
    # memcached:
    #     image: memcached:latest #1.6
    #     restart: always
    #     ports:
    #         - 11211:11211
    #     networks:
    #         - ${NETWORK}

    #############
    # Messenger #
    #############
    # rabbitmq:
    #     image: rabbitmq:latest #3.8
    #     hostname: rabbitmq
    #     environment:
    #         RABBITMQ_DEFAULT_USER: user
    #         RABBITMQ_DEFAULT_PASS: password
    #     ports:
    #         - 5672:5672
    #         - 56720:8080
    #         - 15672:15672
    #     networks: 
    #         - ${NETWORK}

###
# Tuner
# https://github.com/major/MySQLTuner-perl
