version: "3"

services:
    ###########
    # DB ADMIN 
    ###########
    phpmyadmin:
        image: phpmyadmin:latest #5.0
        restart: always
        ports: 
            - 8080:80
        environment: 
            - PMA_ARBITRARY=1
        external_links:
            - mariadb:mariadb
            - mysql:mysql
        networks:
            - phpsrv

    adminer:
        image: adminer:standalone #4.7-standalone
        restart: always
        ports:
            - 8081:8080
        networks:
            - phpsrv

    pgadmin:
        image: dpage/pgadmin4:latest #4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@localhost.fr
            - PGADMIN_DEFAULT_PASSWORD=pass
        external_links:
            - postgres:postgres
        ports: 
            - 8082:80
        networks:
            - phpsrv

    #######
    # SQLITE admin: https://www.phpliteadmin.org
    #######

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin:latest #v1.13
        restart: always
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=redis
        ports: 
            - 8083:80
        networks:
            - phpsrv

    memcachedadmin:
        image: jacksoncage/phpmemcachedadmin:latest
        restart: always
        ports:
            - 8084:80
        networks:
            - phpsrv

networks: 
    phpsrv: