version: '3.4'

services: 
    ###########
    # PHP-FPM # 
    ###########
    fpm: 
        build: 
            context: ./.docker/fpm
            #args:
            #    servername: "my.url_website"
            #    buildno: 1
            #target: FULL
        restart: always
        container_name: fpm
        ports: 
            - 9000:9000
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${DIRECTORY}:/var/www/
            # cli
            - ${DIRECTORY}/.docker/config/srv/phpfpm/php.ini:/etc/php/7.4/cli/php.ini:ro
            - ${DIRECTORY}/.docker/config/srv/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/
            # fpm
            - ${DIRECTORY}/.docker/config/srv/phpfpm/php.ini:/etc/php/7.4/fpm/php.ini:ro
            - ${DIRECTORY}/.docker/config/srv/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
        networks: 
            - phpsrv
    
    # SECOND FPM TO USE LOAD-BALANCING
    fpm2: 
        build: 
            context: ./.docker/fpm
            #target: FULL
        restart: always
        container_name: fpm2
        ports: 
            - 9001:9000
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${DIRECTORY}:/var/www/
            # cli
            - ${DIRECTORY}/.docker/config/srv/phpfpm/php.ini:/etc/php/7.4/cli/php.ini:ro
            - ${DIRECTORY}/.docker/config/srv/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/
            # fpm
            - ${DIRECTORY}/.docker/config/srv/phpfpm/php.ini:/etc/php/7.4/fpm/php.ini:ro
            - ${DIRECTORY}/.docker/config/srv/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
        networks: 
            - phpsrv

networks: 
    phpsrv: