version: '3'

networks: 
    phpsrv:

volumes:
    app_volume:

services: 
    ##########
    # APACHE #
    ##########
    # https://httpd.apache.org/docs
    # apache:
    #     image: httpd:${APACHE_VERSION}
    #     container_name: apache
    #     restart: always
    #     ports: 
    #         - ${APACHE_PORT}:80
    #     volumes:
    #         - ${APP_SOURCE}:/usr/local/apache2/htdocs

    #         # (Un)comment for your own config.
    #         - ${HOST_DIRECTORY}/.docker/server/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    #         - ${HOST_DIRECTORY}/.docker/server/apache/extra/httpd-default.conf:/usr/local/apache2/conf/extra/httpd-default.conf:ro
    #         - ${HOST_DIRECTORY}/.docker/server/apache/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
    #         - ${HOST_DIRECTORY}/.docker/server/apache/extra/httpd-userdir.conf:/usr/local/apache2/conf/extra/httpd-userdir.conf:ro
    #         - ${HOST_DIRECTORY}/.docker/server/apache/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
    #     networks:
    #         - ${NETWORK}

    #########
    # NGINX #
    #########
    # nginx:
    #     image: nginx:${NGINX_VERSION}
    #     container_name: nginx
    #     restart: always
    #     volumes:
    #         - ${HOST_DIRECTORY}/public:/usr/share/nginx/html

    #         # (Un)comment for your own config.
    #         - ${HOST_DIRECTORY}/.docker/server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #         - ${HOST_DIRECTORY}/.docker/server/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    #         #- /nginx/data/cache
    #     ports:
    #         - ${NGINX_PORT}:80
    #     networks: 
    #         - ${NETWORK}

    ###########
    # PHP-FPM # 
    ###########
    fpm: 
        # image: php:8.1-fpm
        container_name: fpm
        build:
            context: .docker/fpm
            target: FULL
        restart: always
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${DIRECTORY}:/var/www/
            # cli
            - ${DIRECTORY}/.docker/config/srv/phpfpm/php.ini:/etc/php/7.4/cli/php.ini:ro
            - ${DIRECTORY}/.docker/config/srv/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/
            # fpm
            - ${DIRECTORY}/.docker/config/srv/phpfpm/php.ini:/etc/php/7.4/fpm/php.ini:ro
            - ${DIRECTORY}/.docker/config/srv/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
        ports: 
            - 9000:9000
        networks:
            - ${NETWORK}

######################
# Other useful boxes #
# https://devilbox.org
# https://easyphp.org
# https://laradock.io
# https://laragon.org
# https://github.com/laraedit/laraedit-docker
# https://hub.docker.com/r/mattrayner/lamp
######################
