version: '3'

networks: 
    phpsrv:

volumes:
    mysql:
    maria:
    pgdata:
    redis:

services: 
    #############
    # DATABASES #
    #############
    # maria:
    #     image: mariadb:${MARIADB_VERSION}
    #     container_name: maria
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: pass
    #         MYSQL_DATABASE: madb
    #     volumes:
    #         - ${HOST_DIRECTORY}/.docker/data/maria:/etc/mysql:ro
    #         - maria:/var/lib/mysql
    #     ports: 
    #         - ${MARIADB_PORT}:3306
    #     networks:
    #         - ${NETWORK}

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
        volumes:
            - ${HOST_DIRECTORY}/.docker/data/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ${HOST_DIRECTORY}/.docker/data/mysql/conf.d/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
            - ${HOST_DIRECTORY}/.docker/data/mysql/initdb.d/:/docker-entrypoint-initdb.d/:ro
            - mysql:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        networks: 
            - ${NETWORK}

    # postgres:
    #     image: postgres:latest #12.4
    #     restart: always
    #     environment:
    #         POSTGRES_USER: user
    #         POSTGRES_PASSWORD: pass
    #         POSTGRES_DB: pgdb
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - pgdata:/var/lib/postgresql/data
    #     networks:
    #         - ${NETWORK}

    # redis:
    #     image: redis:latest #6.0  
    #     restart: always
    #     volumes: 
    #         - ${HOST_DIRECTORY}/.docker/data/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    #         - redis:/data
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - ${NETWORK}
    
    # memcached:
    #     image: memcached:latest #1.6
    #     restart: always
    #     ports:
    #         - 11211:11211
    #     networks:
    #         - ${NETWORK}

    #############
    # Messenger #
    #############
    # rabbitmq:
    #     image: rabbitmq:latest #3.8
    #     hostname: rabbitmq
    #     environment:
    #         RABBITMQ_DEFAULT_USER: user
    #         RABBITMQ_DEFAULT_PASS: password
    #     ports:
    #         - 5672:5672
    #         - 56720:8080
    #         - 15672:15672
    #     networks: 
    #         - phpsrv

###
# Tuner
# https://github.com/major/MySQLTuner-perl
