version: '3'

services: 
    #############
    # DATABASES
    #############
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
        # For Windows users
        #command: "--innodb_use_native_aio=0"
        volumes:
           - ${DIRECTORY}/.docker/config/db/mysql:/etc/mysql:ro
           - mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks: 
            - phpsrv
            
    maria:
        image: mariadb:10.0
        container_name: maria
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: madb
        ports: 
            - 3307:3306
        # For windows users
        #command: "--innodb_use_native_aio=0"
        volumes:
            - ${DIRECTORY}/.docker/config/db/maria:/etc/mysql:ro
            - maria:/var/lib/mysql
        networks:
            - phpsrv

    postgres:
        image: postgres:12.4
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: pgdb
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - phpsrv

    redis:
        image: redis:6.0  
        restart: always
        ports:
            - 6379:6379
        volumes: 
            - ${DIRECTORY}/.docker/config/db/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - redis:/data
        networks:
            - phpsrv
    
    memcached:
        image: memcached:1.6
        restart: always
        ports:
            - 11211:11211
        networks:
            - phpsrv

    #############
    # Messenger #
    #############
    rabbitmq:
        image: rabbitmq:3.8
        hostname: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - 5672:5672
            - 56720:8080
            - 15672:15672
        networks: 
            - phpsrv

networks: 
    phpsrv:

volumes:
    mysql:
    maria:
    pgdata:
    redis:

###
# Tuner
# https://github.com/major/MySQLTuner-perl
#
# Data
# https://min.io