version: '3'

services: 
    ###########
    # PHP-FPM # 
    ###########
    phpfpm: 
        build: .docker/df/phpfpm
        restart: always
        working_dir: /var/www
        ports: 
            - 9000:9000
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/var/www/
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/:/etc/php/7.4/:ro
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/
            
            # sqlite
            - ${WEBSERVER}/${DIRECTORY}/.docker/.data/sqlite/:/sqlite/
        networks: 
            - phpenv
    
    # SECOND FPM TO TRY LOAD-BALANCING
    phpfpm2: 
        build: .docker/df/phpfpm
        restart: always
        working_dir: /var/www
        ports: 
            - 9001:9000
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/var/www/
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/:/etc/php/7.4/:ro
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/
            
            # sqlite
            - ${WEBSERVER}/${DIRECTORY}/.docker/.data/sqlite/:/sqlite/
        networks: 
            - phpenv

networks: 
    phpext: