version: '3'

networks: 
    phpsrv:

volumes:
    app_volume:
    phpfpm_home_volume:

services: 
    ###########
    # PHP-FPM #
    ###########
    phpfpm: 
        image: php:${PHPFPM_VERSION}
        # build:
        #     context: .docker/server/php/dockerfile
        #     target: FULL
        container_name: phpfpm
        restart: always
        environment:
            # (Un)comment for your own config.
            - MARIADB_DSN=mysql:host=mariadb;port=${MARIADB_PORT};dbname=madb
            - MYSQL_DSN=mysql:host=mysql;port=${MYSQL_PORT};dbname=mydb
        volumes:
            - ${APP_SOURCE_PATH}:${APP_CONTAINER_PATH}
            - ${HOST_DIRECTORY}/.docker/.home/Makefile:/root/Makefile
            - phpfpm_home_volume:/root

            # (Un)comment for your own config.
            ### php
            - ${HOST_DIRECTORY}/.docker/server/phpfpm/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ${HOST_DIRECTORY}/.docker/server/phpfpm/php/conf.d/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
            ### fpm
            - ${HOST_DIRECTORY}/.docker/server/phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ${HOST_DIRECTORY}/.docker/server/phpfpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
        # You can use this command to run with minimum extensions.
        command: bash -c "docker-php-ext-install pdo_mysql && php-fpm"
        ports: 
            - ${PHPFPM_PORT}:9000
        networks:
            - ${NETWORK}

    ##########
    # APACHE #
    ##########
    apache:
        image: httpd:${APACHE_VERSION}
        container_name: apache
        restart: always
        depends_on:
            - phpfpm
        volumes:
            - ${APP_SOURCE_PATH}:${APP_CONTAINER_PATH}

            # (Un)comment for your own config.
            - ${HOST_DIRECTORY}/.docker/server/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
            - ${HOST_DIRECTORY}/.docker/server/apache/httpd-custom.conf:/usr/local/apache2/conf/httpd-custom.conf:ro
            - ${HOST_DIRECTORY}/.docker/server/apache/my-extra:/usr/local/apache2/conf/my-extra:ro
        ports: 
            - ${APACHE_PORT}:80
        networks:
            - ${NETWORK}

    #########
    # NGINX #
    #########
    # nginx:
    #     image: nginx:${NGINX_VERSION}
    #     container_name: nginx
    #     restart: always
    #     depends_on:
    #         - phpfpm
    #     volumes:
    #         - ${APP_SOURCE_PATH}:${APP_CONTAINER_PATH}

    #         # (Un)comment for your own config.
    #         - ${HOST_DIRECTORY}/.docker/server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #         - ${HOST_DIRECTORY}/.docker/server/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    #     ports:
    #         - ${NGINX_PORT}:80
    #     networks: 
    #         - ${NETWORK}

    #################
    # PROXY - CACHE #
    #################
    # haproxy:
    #     image: haproxy:latest #2.2
    #     restart: always
    #     ports:
    #         - 8010:80
    #         - 51510:51510
    #     volumes:
    #         - ${HOST_DIRECTORY}/.docker/config/proxy/haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
    #     networks:
    #         - ${NETWORK}

    # varnish: 
    #     image: varnish:latest #6.0
    #     restart: always
    #     ports:
    #         - 8011:80
    #     volumes:
    #         - ${HOST_DIRECTORY}/.docker/config/proxy/varnish:/etc/varnish/
    #     networks:
    #         - ${NETWORK}

    ############
    # Selenium # 
    ############
    # selenium:
    #     image: nkovacs/selenium-standalone-phantomjs:latest
    #     restart: always
    #     ports:
    #         - 4444:4444
    #         - 5900:5900
    #     volumes:
    #         - ${APP_SOURCE}:/appli
    #     networks: 
    #         - ${NETWORK}

######################
# Other useful boxes #
# https://devilbox.org
# https://easyphp.org
# https://laradock.io
# https://laragon.org
# https://github.com/laraedit/laraedit-docker
# https://hub.docker.com/r/mattrayner/lamp
######################
