###########################################
# THIS IS A TEMPLATE DOCKER CONFIGURATION #
# UN(COMMENT) FOR YOUR OWN USAGE          #
###########################################

version: '3.4'

services:
    ###########
    # DB ADMIN 
    ###########
    phpmyadmin:
        image: phpmyadmin:5.0
        restart: always
        ports: 
            - 8080:80
        environment: 
            - PMA_ARBITRARY=1
        external_links:
            - mariadb:mariadb
            - mysql:mysql
        networks:
            - ${NETWORK}

    adminer:
        image: adminer:4.7-standalone
        restart: always
        ports:
            - 8081:8080
        networks:
            - ${NETWORK}

    pgadmin:
        image: dpage/pgadmin4:4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@localhost.fr
            - PGADMIN_DEFAULT_PASSWORD=pass
        external_links:
            - postgres:postgres
        ports: 
            - 8082:80
        networks:
            - ${NETWORK}

    #######
    # SQLITE admin: https://www.phpliteadmin.org
    #######

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin:1.13
        restart: always
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=redis
        ports: 
            - 8083:80
        networks:
            - ${NETWORK}

    memcachedadmin:
        image: jacksoncage/phpmemcachedadmin:latest
        restart: always
        ports:
            - 8084:80
        networks:
            - ${NETWORK}

networks: 
    phpsrv:
