version: "3"

services:
    #################
    # PROXY - CACHE #
    #################
    haproxy:
        image: haproxy:latst #2.2
        restart: always
        ports:
            - 8010:80
            - 51510:51510
        volumes:
            - ${DIRECTORY}/.docker/config/proxy/haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
        networks:
            - phpsrv

    varnish: 
        image: varnish:latest #6.0
        restart: always
        ports:
            - 8011:80
        volumes:
            - ${DIRECTORY}/.docker/config/proxy/varnish:/etc/varnish/
        networks:
            - phpsrv

networks: 
    phpsrv: