version: '3'

services:
    #################
    # PROXY - CACHE #
    #################
    haproxy:
        image: haproxy:latest #2.2
        restart: always
        ports:
            - 8010:80
            - 51510:51510
        volumes:
            - ${HOST_DIRECTORY}/.docker/config/proxy/haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
        networks:
            - ${NETWORK}

    varnish: 
        image: varnish:latest #6.0
        restart: always
        ports:
            - 8011:80
        volumes:
            - ${HOST_DIRECTORY}/.docker/config/proxy/varnish:/etc/varnish/
        networks:
            - ${NETWORK}

networks: 
    phpsrv: