version: "3"

services:
    ###########
    # DB ADMIN 
    ###########
    phpmyadmin:
        image: phpmyadmin:5.0
        restart: always
        ports: 
            - 8080:80
        environment: 
            - PMA_ARBITRARY=1
        external_links:
            - mariadb:mariadb
            - mysql:mysql
        networks:
            - phpenv

    adminer:
        image: adminer:4.7-standalone
        restart: always
        ports:
            - 8081:8080
        networks:
            - phpenv

    pgadmin:
        image: dpage/pgadmin4:4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@localhost.fr
            - PGADMIN_DEFAULT_PASSWORD=pass
        external_links:
            - postgres:postgres
        ports: 
            - 8082:80
        networks:
            - phpenv

    #######
    # SQLITE admin: https://www.phpliteadmin.org
    #######

    # mongo_express:
    #     image: mongo-express
    #     ports:
    #         - 8090:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: root
    #         ME_CONFIG_MONGODB_SERVER: mongodb
    #         ME_CONFIG_MONGODB_AUTH_DATABASE : mongo
    #         ME_CONFIG_MONGODB_AUTH_USERNAME : user
    #         ME_CONFIG_MONGODB_AUTH_PASSWORD : p@ss
    #     networks:
    #         - phpenv

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin:v1.13
        restart: always
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=redis
        ports: 
            - 8083:80
        networks:
            - phpenv

    memcachedadmin:
        image: jacksoncage/phpmemcachedadmin
        restart: always
        ports:
            - 8084:80
        networks:
            - phpenv

networks: 
    phpenv: