name: PHP Composer

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    - name: Install Docker prerequisite
      run: |
        sudo apt-get update
        sudo apt-get remove docker docker-engine docker.io containerd runc
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Install Docker cli
      run: sudo apt-get install docker-ce docker-ce-cli containerd.io

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
