name: PhpEnv-Server

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  run-fpm:
    name: Get docker and run containers
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: clymate/docker-action@v1
    
    - name: Check fpm
      run: |
        sudo source .env
        cd ./.docker
        sudo docker-compose -f 'docker-compose-fpm.yml' up --build -d
        sudo make container_ps
        sudo docker run --rm fpm bash -c "/var/www/public/index.php"

  run-srv:
    name: Get docker and run containers
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: clymate/docker-action@v1
    
    - name: Check srv
      run: |
        sudo source .env
        cd ./.docker
        sudo docker-compose -f 'docker-compose-fpm.yml' up --build -d
        docker-compose -f 'docker-compose-srv.yml' up --build -d
        make container_ps
        sudo docker run --rm fpm bash -c "/var/www/public/index.php"