name: PHP Composer

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    - name: Install Docker cli
      run: | 
        cd /tmp
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Run hello-world
      run: sudo docker run hello-world

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
