name: PhpEnv-Server

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  get_and_run:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    ###
    # https://docs.docker.com/engine/install/ubuntu/
    ###
    - name: Install Docker cli
      run: |
        cd /tmp
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        sudo echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Run makefile
      run: |
        cd ./.docker
        docker-compose -f 'docker-compose-fpm.yml' up --build -d

    - name: Check running containers
      run: sudo make container_ps

    - name: Check servers
      run: sudo docker run --rm fpm bash -c "/var/www/public/index.php"