name: PhpEnv-Server

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    ###
    # https://docs.docker.com/engine/install/ubuntu/
    ###
    - name: Update
      run: sudo apt-get update

    - name: Certs
      run: sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

    - name: key
      run: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Sources list
      run: sudo echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker cli
      run: | 
        cd /tmp
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Run hello-world
      run: sudo docker run hello-world

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
