name: PhpEnv-Server

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  run-fpm:
    name: Check fpm
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: clymate/docker-action@v1

    - name: Compose fpm and srv
        #sudo docker-compose -f 'docker-compose-fpm.yml' up --build -d
        #docker-compose -f 'docker-compose-srv.yml' up --build -d
        #make container_ps
      run: |
        source .env && cd ./.docker
        env
    
    - name: Check fpm
      run: sudo docker run --rm fpm bash -c "/var/www/public/index.php"

  run-srv:
    name: Check srv
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: clymate/docker-action@v1
    
    - name: Compose fpm and srv
      run: |
        source .env && cd ./.docker
        sudo docker-compose -f 'docker-compose-fpm.yml' up --build -d
        docker-compose -f 'docker-compose-srv.yml' up --build -d
        make container_ps

    - name: Check srv
      run: sudo docker run --rm fpm bash -c "/var/www/public/index.php"