name: PHP Composer

on:
  push:
    branches: [ main, dev, docker-test ]
  pull_request:
    branches: [ main, dev, docker-test ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    - name: Install Docker cli from .deb
      run: | 
        sudo wget https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_20.10.5~3-0~ubuntu-bionic_amd64.deb /tmp
        sudo dpkg -i /tmp/docker-ce-cli_20.10.5~3-0~ubuntu-bionic_amd64.deb

    # - name: Install Docker cli
    #   run: sudo apt-get install docker-ce docker-ce-cli containerd.io

      # - name: Run hello
      #   run: sudo docker run hello-world

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
